const AXIOS_CONFIG_KEYS = new Set([
  'adapter',
  'auth',
  'baseURL',
  'data',
  'decompress',
  'headers',
  'httpAgent',
  'httpsAgent',
  'maxBodyLength',
  'maxContentLength',
  'maxRedirects',
  'onDownloadProgress',
  'onUploadProgress',
  'params',
  'paramsSerializer',
  'proxy',
  'responseEncoding',
  'responseType',
  'signal',
  'timeout',
  'timeoutErrorMessage',
  'transformRequest',
  'transformResponse',
  'transitional',
  'url',
  'validateStatus',
  'withCredentials',
  'xsrfCookieName',
  'xsrfHeaderName'
]);

module.exports = { AXIOS_CONFIG_KEYS };
